const consts = {
    ADD_NEW_USER: 'ADD_NEW_USER',
    JOIN_CHATROOM: 'JOIN_CHATROOM',
    MESSAGE_FETCHED: 'MESSAGE_FETCHED',
    CHAT_FETCHED: 'CHAT_FETCHED',
    CONNECTED_TO_SOCKET: 'CONNECTED_TO_SOCKET'
}

export default consts