const consts = {
    ADD_NEW_USER: 'ADD_NEW_USER',
    JOINING_CHATROOM: 'JOINING_CHATROOM',
    JOINED_CHATROOM: 'JOIN_CHATROOM',
    MESSAGES_FETCHED: 'MESSAGES_FETCHED',
    MESSAGE_FETCHED: 'MESSAGE_FETCHED',
    CHATS_FETCHED: 'CHATS_FETCHED',
    CONNECTED_TO_SOCKET: 'CONNECTED_TO_SOCKET',
    REQUEST_CHAT_PENDING: 'REQUEST_CHAT_PENDING',
    REQUEST_CHAT_DONE: 'REQUEST_CHAT_DONE',
    CHANGE_CURRENT_CHATROOM: 'CHANGE_CURRENT_CHATROOM',
    auth: {
        REMOVE_USER: 'REMOVE_USER'
    },
    chat: {
        USERS_LIST_FETCHED: 'USERS_LIST_FETCHED',
        NEW_CHAT_FETCHED: 'NEW_CHAT_FETCHED'
    }
}

export default consts