const consts = {
    ADD_NEW_USER: 'ADD_NEW_USER',
    JOIN_CHATROOM: 'JOIN_CHATROOM',
    MESSAGE_FETCHED: 'MESSAGE_FETCHED',
    CHAT_FETCHED: 'CHAT_FETCHED',
    CHATS_FETCHED: 'CHATS_FETCHED',
    CONNECTED_TO_SOCKET: 'CONNECTED_TO_SOCKET',
    REQUEST_CHAT_PENDING: 'REQUEST_CHAT_PENDING',
    REQUEST_CHAT_DONE: 'REQUEST_CHAT_DONE'
}

export default consts